CREATE DATABASE IF NOT EXISTS todos_db;

USE todos_db;

CREATE TABLE IF NOT EXISTS users (
  _id INT PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
  _id INT PRIMARY KEY AUTO_INCREMENT,
  text VARCHAR(100),
  checked BOOL DEFAULT false,
  userID INT NOT NULL,
  FOREIGN KEY (userID) REFERENCES users (_id) ON DELETE CASCADE
);
